name: Deploy NodeJS Application to AWS

on: 
  push: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key:  ${{ secrets.SSH_KEY }}   
          script: |
            cd /home/ubuntu/nodejs-application-deploy-github-actions
            git pull
            docker compose up -d --build